"""
Django settings for darpan project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""


import environ
import os  # isort:skip
from os.path import dirname, abspath, join


_ = lambda s: s

env = environ.Env()
ROOT_DIR = (
    environ.Path(__file__) - 3
) 

DATA_DIR = (
    environ.Path(__file__) - 3
)



READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=True)
if READ_DOT_ENV_FILE:
    # OS environment variables take precedence over variables from .env
    env_path = str(ROOT_DIR.path(".env"))
    env.read_env(env_path)






# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", False)




# Application definition





ROOT_URLCONF = 'config.urls'



WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_ROOT = str(DATA_DIR("media"))
STATIC_ROOT = str(DATA_DIR("staticfiles"))

STATICFILES_DIRS = [str(ROOT_DIR.path("darpan", "static"))]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

SITE_ID = 1


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        "DIRS": [str(ROOT_DIR.path('darpan', 'templates'))],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]


MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',

    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'request.middleware.RequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    
    'django.middleware.cache.FetchFromCacheMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
]

# Key in `CACHES` dict
CACHE_MIDDLEWARE_ALIAS = 'default'

# Additional prefix for cache keys
CACHE_MIDDLEWARE_KEY_PREFIX = 'django_cache_'

# Cache key TTL in seconds
CACHE_MIDDLEWARE_SECONDS = 600

DJANGO_APPS = [
    'users.apps.UsersConfig',
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities',
    'djangocms_file',
    'djangocms_icon',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
]

THIRD_PARTY_APPS = [
    'constance',
    'constance.backends.database',
    
    'cacheops',
    'compressor',
    'request',
    'django_extensions',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]


LOCAL_APPS = ['darpan',]



# https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

AUTH_USER_MODEL = 'users.User'

LANGUAGES = (
    ## Customize this
    ('pt-br', _('pt-br')),
    ('en-us', _('en-us')),
)

CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'code': 'pt-br',
            'name': _('pt-br'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
        {
            'code': 'en-us',
            'name': _('en-us'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },

    ],
    'default': {
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}


LOCALE_PATHS = [ROOT_DIR.path("locale")]


CMS_TEMPLATES = (
    ## Customize this
    ('wrapped.html', 'Wrapped'),
    ('fullwidth.html', 'Fullwidth'),
    ('sidebar_left.html', 'Sidebar Left'),
    ('sidebar_right.html', 'Sidebar Right'),
    ('bolobolo.html', "Bolo'bolo"),
    ('bolobolo_note.html', "Bolo'bolo - Nota"),
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}



DATABASES = {
    "default": env.db("DATABASE_URL", default="sqlite:///project.db")
}
DATABASES["default"]["ATOMIC_REQUESTS"] = True


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
CACHEOPS_REDIS = "redis://localhost:6379/1"
CACHEOPS = {
    
    '*.*': {'timeout': 60*60},
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

DJANGOCMS_PICTURE_TEMPLATES = [
    ('background', _('Background image')),
    ('main', _('Main image')),
    ('lazy', _('Lazy image')),
]



REQUEST_IGNORE_PATHS = (
    r'^pt-br/admin/',
    r'^media/',
)

REQUEST_IGNORE_USERNAME = (
    'admin', 'darpan'
)





SENDGRID_API_KEY = env('SENDGRID_API_KEY')

COMPRESS_ENABLED = True


#RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_PUBLIC_KEY_V2')
#RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_PRIVATE_KEY_V2')
#RECAPTCHA_REQUIRED_SCORE = 0.5


CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_DATABASE_CACHE_BACKEND = 'default'
CONSTANCE_CONFIG = {
    'TELEGRAM_URL': ('https://t.me/DarpanDevaTantra', 'Telegram URL', str),
    'WHATSAPP_URL': ('https://wa.me/5511930628878?text=Ol%C3%A1%2C%20peguei%20seu%20contato%20no%20site%20DarpanDeva.com%20e%20fiquei%20interessado%20no%20seu%20trabalho!', 'Whatsapp URL', str),
}
