# Generated by Django 2.2 on 2019-12-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darpan', '0003_auto_20191221_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Target'),
        ),
    ]
