# Generated by Django 2.2 on 2019-12-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darpan', '0004_externallink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkaccess',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='darpan.ExternalLink'),
        ),
    ]
