# Generated by Django 2.2 on 2019-12-22 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darpan', '0005_auto_20191221_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkaccess',
            name='url',
        ),
        migrations.AlterField(
            model_name='externallink',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Link Target'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkaccess',
            name='link',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='access', to='darpan.ExternalLink'),
            preserve_default=False,
        ),
    ]
