# Generated by Django 2.2 on 2020-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darpan', '0010_auto_20200126_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lazypicture',
            name='placeholder_base64_picture',
            field=models.CharField(blank=True, help_text='If provided, overrides the embedded image. Certain options such as cropping are not applicable to external images.', max_length=32768, null=True, verbose_name='Placeholder Base64 image'),
        ),
    ]
