# Generated by Django 2.2 on 2020-01-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darpan', '0011_auto_20200126_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='lazypicture',
            name='self_link',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wraps with a link to the original image'),
        ),
        migrations.AlterField(
            model_name='lazypicture',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('background', 'Background image'), ('main', 'Main image'), ('lazy', 'Lazy image')], default='default', max_length=255, verbose_name='Template'),
        ),
    ]
