# Generated by Django 2.2 on 2020-01-26 17:12

from django.db import migrations
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('darpan', '0012_auto_20200126_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='lazypicture',
            name='span_attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Span attributes'),
        ),
    ]
